{% set name = "qttranslations" %}
{% set version = "6.7.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: dcc762acac043b9bb5e4d369b6d6f53e0ecfcf76a408fe0db5f7ef071c9d6dc8
    folder: {{ name }}

build:
  number: 2
  skip: true  # [ppc64le or s390x or (osx and x86_64)]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # TODO: map CDT libdrm-devel to new X11 package
    # - { cdt('libdrm-devel') }
    # TODO: map CDT mesa-libgbm to new X11 package
    # - { cdt('mesa-libgbm') }
    # TODO: map CDT mesa-libegl-devel to new X11 package
    # - { cdt('mesa-libegl-devel') }
    # TODO: map CDT libselinux to new X11 package
    # - { cdt('libselinux') }
    - pkg-config  # [unix]
    - bison  # [linux]
    - flex  # [linux]
    - gperf  # [linux]
    - jom  # [win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - m2-gperf  # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase {{ version }}
    - qttools {{ version }}
    - libglx
    - libegl
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxau
    - libgl-devel
    - mesa-dri-drivers
    - xcb-util
    - xcb-util-image
    - xcb-util-keysyms
    - xcb-util-renderutil
    - xcb-util-wm
    - xorg-xproto
    - xorg-libxext
    - xorg-libxdamage
    - xorg-libxfixes
    - xorg-libxxf86vm
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

about:
  home: https://www.qt.io/
  license: BSD-3-Clause
  license_file: {{ name }}/LICENSES/BSD-3-Clause.txt
  license_family: BSD
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}

extra:
  skip-lints:
    # nothing relevant to be tested here
    - missing_tests