{% set name = "qttranslations" %}
{% set version = "6.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: c73bb6281ed365c0f954f4b1b6e1b13e1b3fefd94854f46fcd9a412f641f7ed6
    folder: {{ name }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config   # [unix]
    - bison        # [linux]
    - flex         # [linux]
    - gperf        # [linux]
    - jom          # [win]
    - msys2-bison  # [win]
    - msys2-flex   # [win]
    - msys2-gperf  # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase-devel {{ version }}
    - qttools {{ version }}
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

about:
  home: https://www.qt.io/
  license: BSD-3-Clause
  license_file: {{ name }}/LICENSES/BSD-3-Clause.txt
  license_family: BSD
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}

extra:
  skip-lints:
    # nothing relevant to be tested here
    - missing_tests