{% set name = "qttranslations" %}
{% set version = "6.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: 9761a1a555f447cdeba79fdec6a705dee8a7882ac10c12e85f49467ddd01a741
    folder: {{ name }}

build:
  number: 0
  skip: true  # [osx and x86_64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config   # [unix]
    - bison        # [linux]
    - flex         # [linux]
    - gperf        # [linux]
    - jom          # [win]
    - msys2-bison  # [win]
    - msys2-flex   # [win]
    - msys2-gperf  # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase-devel {{ version }}
    - qttools {{ version }}
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

about:
  home: https://www.qt.io/
  license: BSD-3-Clause
  license_file: {{ name }}/LICENSES/BSD-3-Clause.txt
  license_family: BSD
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}

extra:
  skip-lints:
    # nothing relevant to be tested here
    - missing_tests