{% set name = "qttranslations" %}
{% set version = "6.7.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/archive/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: dcc762acac043b9bb5e4d369b6d6f53e0ecfcf76a408fe0db5f7ef071c9d6dc8
    folder: {{ name }}

build:
  number: 1
  skip: true  # [osx and x86_64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
    - bison  # [linux]
    - flex  # [linux]
    - gperf  # [linux]
    - jom  # [win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - m2-gperf  # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase {{ version }}
    - qttools {{ version }}
    # X11 dependencies
    - libgl-devel  # [linux]
    - libegl-devel  # [linux]
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

about:
  home: https://www.qt.io/
  license: BSD-3-Clause
  license_file: {{ name }}/LICENSES/BSD-3-Clause.txt
  license_family: BSD
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}

extra:
  skip-lints:
    # nothing relevant to be tested here
    - missing_tests